/*
 * Sa-mpEx
 * =======
 * Include file for Sa-mpEx library module.
 *
 * Module name: Extra
 *
 * Module version: 1.0
 *
 * Thanks to everyone who helped.
 * I really appreciate all your words.
 *
 * Please, keep all the credits.
 * If you want to contribute this project,
 * feel free to do it.
 *
 * Any file can be used and feel free to use its'
 * source code.
 *
 * On Discord, feel free to contact me about the library.
 *
 * Big thanks to OPEN MULTIPLAYER community - staff team and
 * other users, contributors, admins etc.
 *
 *                  DentisT.
 *
 *
 */

// Anti de-amx function:

#include "s_isnull"

sampex_antideamx()
{
	new
		a
		[]
		[] 
	=
	{
	    "Unarmed (Fist)",
	    "Brass K"
	}
	;
	#pragma unused a
}

#include "s_amx_extra"