/*
 * Sa-mpEx
 * =======
 * Include file for Sa-mpEx library module.
 *
 * Module name: INI CORE
 *
 * Module version: 1.0
 *
 * Thanks to everyone who helped.
 * I really appreciate all your words.
 *
 * Please, keep all the credits.
 * If you want to contribute this project,
 * feel free to do it.
 *
 * Any file can be used and feel free to use its'
 * source code.
 *
 * On Discord, feel free to contact me about the library.
 *
 * Big thanks to OPEN MULTIPLAYER community - staff team and
 * other users, contributors, admins etc.
 *
 *                  DentisT.
 *
 *
 */


#include "s_inicore\s_crfile"
#include "s_inicore\s_inifloat"
#include "s_inicore\s_iniboolean"

#include "s_inicore\s_intcore"
#include "s_inicore\s_inicheck"

#include "s_inicore\s_txtcopy"

#include "s_inicore\s_inifilemng"