/*
 * Sa-mpEx
 * =======
 * Include file for Sa-mpEx library module.
 *
 * Module name: # pragma
 *
 * Module version: 1.0
 *
 * Thanks to everyone who helped.
 * I really appreciate all your words.
 *
 * Please, keep all the credits.
 * If you want to contribute this project,
 * feel free to do it.
 *
 * Any file can be used and feel free to use its'
 * source code.
 *
 * On Discord, feel free to contact me about the library.
 *
 * Big thanks to OPEN MULTIPLAYER community - staff team and
 * other users, contributors, admins etc.
 *
 *                  DentisT.
 *
 *
 */


/*=============================================
Pragmas for SA-MP functions module
=============================================*/

// For never-used warnings in FlyMode include

#pragma unused Flying
#pragma unused StartFly
#pragma unused StopFly

// For streamer funcs:

#pragma unused big_map_objects
#pragma unused middlesized_map_objects

#if defined sampex_stockavoid

#pragma unused sampex_createdynamicobject

#endif
