/*-------------------------------------------------------

		=====================
		Sa-mpEx Configuration
		=====================

-------------------------------------------------------*/

#include "s_configdata\s_scriptentry_config.inc"
#include "s_configdata\s_playerdata_config.inc"
#include "s_configdata\s_hooks_config.inc"
#include "s_configdata\s_extendeds_config.inc"
#include "s_configdata\s_storage_config.inc"
#include "s_configdata\s_game_config.inc"
#include "s_configdata\s_streamer_config.inc"
#include "s_configdata\s_commands_config.inc"

#include "s_configdata\sampex_hookinfo_display.inc"
#include "s_configdata\sampex_include_stdlib.inc"